version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dq-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secure_pass
      POSTGRES_DB: dataquartz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
