/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as WizardRouteImport } from './routes/_wizard'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppActiveDemosRouteImport } from './routes/_app.active-demos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppVoiceAgentRouteImport } from './routes/_app.voice-agent'
import { Route as WizardBuildDemoRouteImport } from './routes/_wizard.build-demo'
import { Route as WizardClarificationRouteImport } from './routes/_wizard.clarification'
import { Route as WizardDemoPreviewRouteImport } from './routes/_wizard.demo-preview'
import { Route as WizardPipelineRouteImport } from './routes/_wizard.pipeline'
import { Route as WizardUploadRouteImport } from './routes/_wizard.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const WizardRoute = WizardRouteImport.update({
  id: '/_wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActiveDemosRoute = AppActiveDemosRouteImport.update({
  id: '/active-demos',
  path: '/active-demos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceAgentRoute = AppVoiceAgentRouteImport.update({
  id: '/voice-agent',
  path: '/voice-agent',
  getParentRoute: () => AppRoute,
} as any)
const WizardBuildDemoRoute = WizardBuildDemoRouteImport.update({
  id: '/build-demo',
  path: '/build-demo',
  getParentRoute: () => WizardRoute,
} as any)
const WizardClarificationRoute = WizardClarificationRouteImport.update({
  id: '/clarification',
  path: '/clarification',
  getParentRoute: () => WizardRoute,
} as any)
const WizardDemoPreviewRoute = WizardDemoPreviewRouteImport.update({
  id: '/demo-preview',
  path: '/demo-preview',
  getParentRoute: () => WizardRoute,
} as any)
const WizardPipelineRoute = WizardPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => WizardRoute,
} as any)
const WizardUploadRoute = WizardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => WizardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/active-demos': typeof AppActiveDemosRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/settings': typeof AppSettingsRoute
  '/voice-agent': typeof AppVoiceAgentRoute
  '/build-demo': typeof WizardBuildDemoRoute
  '/clarification': typeof WizardClarificationRoute
  '/demo-preview': typeof WizardDemoPreviewRoute
  '/pipeline': typeof WizardPipelineRoute
  '/upload': typeof WizardUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/active-demos': typeof AppActiveDemosRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/settings': typeof AppSettingsRoute
  '/voice-agent': typeof AppVoiceAgentRoute
  '/build-demo': typeof WizardBuildDemoRoute
  '/clarification': typeof WizardClarificationRoute
  '/demo-preview': typeof WizardDemoPreviewRoute
  '/pipeline': typeof WizardPipelineRoute
  '/upload': typeof WizardUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_wizard': typeof WizardRouteWithChildren
  '/portal': typeof PortalRoute
  '/pricing': typeof PricingRoute
  '/_app/active-demos': typeof AppActiveDemosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/voice-agent': typeof AppVoiceAgentRoute
  '/_wizard/build-demo': typeof WizardBuildDemoRoute
  '/_wizard/clarification': typeof WizardClarificationRoute
  '/_wizard/demo-preview': typeof WizardDemoPreviewRoute
  '/_wizard/pipeline': typeof WizardPipelineRoute
  '/_wizard/upload': typeof WizardUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/pricing'
    | '/active-demos'
    | '/dashboard'
    | '/feedback'
    | '/settings'
    | '/voice-agent'
    | '/build-demo'
    | '/clarification'
    | '/demo-preview'
    | '/pipeline'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal'
    | '/pricing'
    | '/active-demos'
    | '/dashboard'
    | '/feedback'
    | '/settings'
    | '/voice-agent'
    | '/build-demo'
    | '/clarification'
    | '/demo-preview'
    | '/pipeline'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_wizard'
    | '/portal'
    | '/pricing'
    | '/_app/active-demos'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_app/settings'
    | '/_app/voice-agent'
    | '/_wizard/build-demo'
    | '/_wizard/clarification'
    | '/_wizard/demo-preview'
    | '/_wizard/pipeline'
    | '/_wizard/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  WizardRoute: typeof WizardRouteWithChildren
  PortalRoute: typeof PortalRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_wizard': {
      id: '/_wizard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/active-demos': {
      id: '/_app/active-demos'
      path: '/active-demos'
      fullPath: '/active-demos'
      preLoaderRoute: typeof AppActiveDemosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice-agent': {
      id: '/_app/voice-agent'
      path: '/voice-agent'
      fullPath: '/voice-agent'
      preLoaderRoute: typeof AppVoiceAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_wizard/build-demo': {
      id: '/_wizard/build-demo'
      path: '/build-demo'
      fullPath: '/build-demo'
      preLoaderRoute: typeof WizardBuildDemoRouteImport
      parentRoute: typeof WizardRoute
    }
    '/_wizard/clarification': {
      id: '/_wizard/clarification'
      path: '/clarification'
      fullPath: '/clarification'
      preLoaderRoute: typeof WizardClarificationRouteImport
      parentRoute: typeof WizardRoute
    }
    '/_wizard/demo-preview': {
      id: '/_wizard/demo-preview'
      path: '/demo-preview'
      fullPath: '/demo-preview'
      preLoaderRoute: typeof WizardDemoPreviewRouteImport
      parentRoute: typeof WizardRoute
    }
    '/_wizard/pipeline': {
      id: '/_wizard/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof WizardPipelineRouteImport
      parentRoute: typeof WizardRoute
    }
    '/_wizard/upload': {
      id: '/_wizard/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof WizardUploadRouteImport
      parentRoute: typeof WizardRoute
    }
  }
}

interface AppRouteChildren {
  AppActiveDemosRoute: typeof AppActiveDemosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVoiceAgentRoute: typeof AppVoiceAgentRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActiveDemosRoute: AppActiveDemosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVoiceAgentRoute: AppVoiceAgentRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WizardRouteChildren {
  WizardBuildDemoRoute: typeof WizardBuildDemoRoute
  WizardClarificationRoute: typeof WizardClarificationRoute
  WizardDemoPreviewRoute: typeof WizardDemoPreviewRoute
  WizardPipelineRoute: typeof WizardPipelineRoute
  WizardUploadRoute: typeof WizardUploadRoute
}

const WizardRouteChildren: WizardRouteChildren = {
  WizardBuildDemoRoute: WizardBuildDemoRoute,
  WizardClarificationRoute: WizardClarificationRoute,
  WizardDemoPreviewRoute: WizardDemoPreviewRoute,
  WizardPipelineRoute: WizardPipelineRoute,
  WizardUploadRoute: WizardUploadRoute,
}

const WizardRouteWithChildren =
  WizardRoute._addFileChildren(WizardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  WizardRoute: WizardRouteWithChildren,
  PortalRoute: PortalRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
