/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as DemoPreviewRouteImport } from './routes/demo-preview'
import { Route as ClarificationRouteImport } from './routes/clarification'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVoiceAgentRouteImport } from './routes/_app.voice-agent'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResearchProgressRouteImport } from './routes/_app.research-progress'
import { Route as AppNewDemoRouteImport } from './routes/_app.new-demo'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppActiveDemosRouteImport } from './routes/_app.active-demos'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPreviewRoute = DemoPreviewRouteImport.update({
  id: '/demo-preview',
  path: '/demo-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ClarificationRoute = ClarificationRouteImport.update({
  id: '/clarification',
  path: '/clarification',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoiceAgentRoute = AppVoiceAgentRouteImport.update({
  id: '/voice-agent',
  path: '/voice-agent',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchProgressRoute = AppResearchProgressRouteImport.update({
  id: '/research-progress',
  path: '/research-progress',
  getParentRoute: () => AppRoute,
} as any)
const AppNewDemoRoute = AppNewDemoRouteImport.update({
  id: '/new-demo',
  path: '/new-demo',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppActiveDemosRoute = AppActiveDemosRouteImport.update({
  id: '/active-demos',
  path: '/active-demos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clarification': typeof ClarificationRoute
  '/demo-preview': typeof DemoPreviewRoute
  '/pipeline': typeof PipelineRoute
  '/portal': typeof PortalRoute
  '/upload': typeof UploadRoute
  '/active-demos': typeof AppActiveDemosRoute
  '/dashboard': typeof AppDashboardRoute
  '/new-demo': typeof AppNewDemoRoute
  '/research-progress': typeof AppResearchProgressRoute
  '/settings': typeof AppSettingsRoute
  '/voice-agent': typeof AppVoiceAgentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clarification': typeof ClarificationRoute
  '/demo-preview': typeof DemoPreviewRoute
  '/pipeline': typeof PipelineRoute
  '/portal': typeof PortalRoute
  '/upload': typeof UploadRoute
  '/active-demos': typeof AppActiveDemosRoute
  '/dashboard': typeof AppDashboardRoute
  '/new-demo': typeof AppNewDemoRoute
  '/research-progress': typeof AppResearchProgressRoute
  '/settings': typeof AppSettingsRoute
  '/voice-agent': typeof AppVoiceAgentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/clarification': typeof ClarificationRoute
  '/demo-preview': typeof DemoPreviewRoute
  '/pipeline': typeof PipelineRoute
  '/portal': typeof PortalRoute
  '/upload': typeof UploadRoute
  '/_app/active-demos': typeof AppActiveDemosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/new-demo': typeof AppNewDemoRoute
  '/_app/research-progress': typeof AppResearchProgressRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/voice-agent': typeof AppVoiceAgentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clarification'
    | '/demo-preview'
    | '/pipeline'
    | '/portal'
    | '/upload'
    | '/active-demos'
    | '/dashboard'
    | '/new-demo'
    | '/research-progress'
    | '/settings'
    | '/voice-agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clarification'
    | '/demo-preview'
    | '/pipeline'
    | '/portal'
    | '/upload'
    | '/active-demos'
    | '/dashboard'
    | '/new-demo'
    | '/research-progress'
    | '/settings'
    | '/voice-agent'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/clarification'
    | '/demo-preview'
    | '/pipeline'
    | '/portal'
    | '/upload'
    | '/_app/active-demos'
    | '/_app/dashboard'
    | '/_app/new-demo'
    | '/_app/research-progress'
    | '/_app/settings'
    | '/_app/voice-agent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ClarificationRoute: typeof ClarificationRoute
  DemoPreviewRoute: typeof DemoPreviewRoute
  PipelineRoute: typeof PipelineRoute
  PortalRoute: typeof PortalRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-preview': {
      id: '/demo-preview'
      path: '/demo-preview'
      fullPath: '/demo-preview'
      preLoaderRoute: typeof DemoPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarification': {
      id: '/clarification'
      path: '/clarification'
      fullPath: '/clarification'
      preLoaderRoute: typeof ClarificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/voice-agent': {
      id: '/_app/voice-agent'
      path: '/voice-agent'
      fullPath: '/voice-agent'
      preLoaderRoute: typeof AppVoiceAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research-progress': {
      id: '/_app/research-progress'
      path: '/research-progress'
      fullPath: '/research-progress'
      preLoaderRoute: typeof AppResearchProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-demo': {
      id: '/_app/new-demo'
      path: '/new-demo'
      fullPath: '/new-demo'
      preLoaderRoute: typeof AppNewDemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/active-demos': {
      id: '/_app/active-demos'
      path: '/active-demos'
      fullPath: '/active-demos'
      preLoaderRoute: typeof AppActiveDemosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActiveDemosRoute: typeof AppActiveDemosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNewDemoRoute: typeof AppNewDemoRoute
  AppResearchProgressRoute: typeof AppResearchProgressRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVoiceAgentRoute: typeof AppVoiceAgentRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActiveDemosRoute: AppActiveDemosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNewDemoRoute: AppNewDemoRoute,
  AppResearchProgressRoute: AppResearchProgressRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVoiceAgentRoute: AppVoiceAgentRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ClarificationRoute: ClarificationRoute,
  DemoPreviewRoute: DemoPreviewRoute,
  PipelineRoute: PipelineRoute,
  PortalRoute: PortalRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
