"""initial_schema

Revision ID: fea66a6b5ca1
Revises: 
Create Date: 2026-07-15 11:48:32.500563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fea66a6b5ca1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('logo_color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_initials', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demojob',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('research_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('meeting_booked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discoveryresponse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('missed_calls_per_week', sa.Integer(), nullable=False),
    sa.Column('average_booking_value', sa.Float(), nullable=False),
    sa.Column('calculated_monthly_leakage', sa.Float(), nullable=False),
    sa.Column('calendar_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('booking_requirements', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('escalation_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('integration_destination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rendered_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assistant_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('agent_status', sa.Enum('pending', 'active', 'completed', 'failed', name='agentstatus'), nullable=False),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voiceagent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discovery_id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voice_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voiceagent')
    op.drop_table('leads')
    op.drop_table('discoveryresponse')
    op.drop_table('demojob')
    op.drop_table('company')
    # ### end Alembic commands ###
